LAB.NET.MVC/LAB.MVC/Models/TerritoriesView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LAB.MVC.Models
{
    public class TerritoriesView
    {
        [Required(ErrorMessage = "Este campo es requerido.") ]
        public string Id { get; set; }

        [Required(ErrorMessage = "Este campo es requerido.")]
        public string TerritoryDescription { get; set; }
        public int RegionID { get; set; }
    }
}

LAB.NET.MVC/LAB.MVC/Controllers/TerritoriesController.cs
using LAB.Entities;
using LAB.Logic;
using LAB.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LAB.MVC.Controllers
{
    public class TerritoriesController : Controller
    {
        TerritoriesLogic territoriesLogic = new TerritoriesLogic();
        // GET: Territories
        public ActionResult Index()
        {

            List<Entities.Territories> territories = territoriesLogic.GetAll();

            List<TerritoriesView> territoriesViews = territories.Select(s => new TerritoriesView
            {
                Id = s.TerritoryID,
                TerritoryDescription = s.TerritoryDescription
            }).ToList();

            return View(territoriesViews);
        }

        public ActionResult Insert(string id)
        {
            List<SelectListItem> listRegion = new List<SelectListItem>();
            listRegion.Add(new SelectListItem() { Value = "1", Text = "Eastern" });
            listRegion.Add(new SelectListItem() { Value = "2", Text = "Western" });
            listRegion.Add(new SelectListItem() { Value = "3", Text = "Northem" });
            listRegion.Add(new SelectListItem() { Value = "4", Text = "Southem" });
            ViewBag.RegionDD = listRegion;
            TempData["regiones"] = ViewBag.RegionDD;

            TerritoriesView territoriesView = new TerritoriesView();
            if (id != null)
            {
                var territorie = territoriesLogic.GetOne(id);
                territoriesView.TerritoryDescription = territorie.TerritoryDescription;
                territoriesView.RegionID = territorie.RegionID;
                return View(territoriesView);
            }

            return View();
        }

        [HttpPost]
        public ActionResult Insert(TerritoriesView territoriesView)
        {
            ViewBag.RegionDD = TempData["regiones"];
            if (ModelState.IsValid)
            {
                try
                {
                    var territoriesEntity = new Territories();

                    territoriesEntity.TerritoryID = territoriesView.Id;
                    territoriesEntity.TerritoryDescription = territoriesView.TerritoryDescription;
                    territoriesEntity.RegionID = territoriesView.RegionID;

                    var existe = territoriesLogic.Exists(territoriesView.Id);

                    if (existe)
                        territoriesLogic.Update(territoriesEntity);
                    else
                        territoriesLogic.Add(territoriesEntity);
                    return RedirectToAction("Index");

                }
                catch (Exception ex)
                {
                    TempData["message"] = ex.Message;
                    return RedirectToAction("Index", "Error");
                }
            }
            return View(territoriesView);
        }

        public ActionResult Delete(string Id)
        {
            try
            {
                territoriesLogic.Delete(Id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
                return RedirectToAction("Index", "Error");
            }
        }

    }
}

LAB.NET.MVC/LAB.MVC/Views/Territories/Index.cshtml
@model List<LAB.MVC.Models.TerritoriesView>

@{
    ViewBag.Title = "Territories Page";
}

<h1 class="text-center">Consulta de lista actual de territorios.</h1>
<br />
<div>
    @Html.ActionLink("AGREGAR NUEVO TERRITORIO", "Insert", null, new { @class = "btn btn-success stretched-link" })
</div>
<br/>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Descripcion</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    @foreach (var territories in Model)
    {
        <tr>
            <td scope="row">@territories.Id</td>
            <td>@territories.TerritoryDescription</td>
            <td>@Html.ActionLink("Borrar", "Delete", new { id = territories.Id }, new { onclick = "return confirm('¿Esta seguro de que desea eliminar el empleado?')", @class = "btn btn-danger stretched-link" })</td>
            <td>@Html.ActionLink("Modificar", "Insert", new { id = territories.Id }, new { @class = "btn btn-primary stretched-link" })</td>
        </tr>
    }
</table>
<div>
    @Html.ActionLink("AGREGAR NUEVO TERRITORIO", "Insert", null, new { @class = "btn btn-success stretched-link" })
</div>

LAB.NET.MVC/LAB.MVC/Views/Territories/Insert.cshtml
@model LAB.MVC.Models.TerritoriesView
@{
    ViewBag.Title = "Territories Page";

}

@using (Html.BeginForm("Insert", "Territories", FormMethod.Post))
{
    <section>

        <div class="container-fluid mt-5 mb-5">
            <br />
            <h3 class=" text-center">ABM TERRITORIOS</h3>
            <label ID="lblEstado" Font-Size="X-Large" CssClass="text-center" ForeColor="#3333FF"></label>
            <div class="form-group forms">

                <label>ID Territorio:</label>
                @{if (Model != null)
                    { @Html.TextBoxFor(t => t.Id, new { @class = "form-control", MaxLength = "20", Disabled = true })}
                else
                { @Html.TextBoxFor(t => t.Id, new { @class = "form-control", MaxLength = "20", required = "true", id = "txtID" })}
                }

                @Html.ValidationMessageFor(t => t.Id, "", new { @class = "text-danger field-validation-error" })<br />
                <label>Descripcion:</label>
                @Html.TextBoxFor(t => t.TerritoryDescription, new { @class = "form-control", MaxLength = "50", required = "true", id = "txtDescripcion" })
                @Html.ValidationMessageFor(t => t.TerritoryDescription, "", new { @class = "text-danger field-validation-error" })<br />
                <label>Region:</label>
                @Html.DropDownListFor(t => t.RegionID, (IEnumerable<SelectListItem>)ViewBag.RegionDD, new { @class = "form-control" })
                <br />
                <input type="submit" Value="Guardar" class="btn btn-success" style="width:100%" onclick="validate()" />
            </div>
        </div>
    </section>
}
<script>
    function validate() {
        event.preventDefault;
        if ($("#txtID").val().trim().length == 0) {
            $("#txtID").val("");
        }
        if ($("#txtDescripcion").val().trim().length == 0) {
            $("#txtDescripcion").val("");
        }
    }
</script>